using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EnterpriseTaskManager.API.Models.Entities;

/// <summary>
/// Comment on a task with support for AI-generated comments
/// </summary>
public class Comment
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    [Required]
    public Guid TaskId { get; set; }

    [Required]
    public Guid UserId { get; set; }

    [Required]
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Indicates if this comment was generated by AI (e.g., summary)
    /// </summary>
    public bool IsAIGenerated { get; set; } = false;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Navigation properties
    [ForeignKey(nameof(TaskId))]
    public virtual TaskItem Task { get; set; } = null!;

    [ForeignKey(nameof(UserId))]
    public virtual User User { get; set; } = null!;
}
